=== parker1978/ActionTracker/ActionTrackerKit/Sources/DataLayer/Resources/weapons.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Weapons">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Weapon" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <!-- Mandatory fields -->
              <xs:element name="Name" type="xs:string" minOccurs="1"/>
              <xs:element name="Set" type="xs:string" minOccurs="1"/>
              <xs:element name="Deck" type="xs:string" minOccurs="1"/>
              <xs:element name="Count" type="xs:integer" minOccurs="1"/>
              <xs:element name="Category" type="xs:string" minOccurs="1"/>

              <!-- Optional weapon substructures -->
              <xs:element name="Melee" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Range" type="xs:integer" minOccurs="0"/>
                    <xs:element name="Dice" type="xs:integer" minOccurs="0"/>
                    <xs:element name="Accuracy" type="xs:integer" minOccurs="0"/>
                    <xs:element name="Damage" type="xs:integer" minOccurs="0"/>
                    <xs:element name="Overload" type="xs:integer" minOccurs="0"/>
                    <xs:element name="Kill_Noise" type="xs:boolean" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="Ranged" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Ammo_Type" type="xs:string" minOccurs="0"/>
                    <xs:element name="Range_Min" type="xs:integer" minOccurs="0"/>
                    <xs:element name="Range_Max" type="xs:integer" minOccurs="0"/>
                    <xs:element name="Dice" type="xs:integer" minOccurs="0"/>
                    <xs:element name="Accuracy" type="xs:integer" minOccurs="0"/>
                    <xs:element name="Damage" type="xs:integer" minOccurs="0"/>
                    <xs:element name="Overload" type="xs:integer" minOccurs="0"/>
                    <xs:element name="Kill_Noise" type="xs:boolean" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
              <!-- Optional common fields -->
              <xs:element name="Open_Door" type="xs:boolean" minOccurs="0"/>
              <xs:element name="Door_Noise" type="xs:boolean" minOccurs="0"/>
              <xs:element name="Dual" type="xs:boolean" minOccurs="0"/>
              <xs:element name="Special" type="xs:string" minOccurs="0"/>

            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="version" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== parker1978/ActionTracker/ActionTrackerKit/Sources/DataLayer/Resources/weapons.xml
<?xml version='1.0' encoding='utf-8'?>
<Weapons version="2.3.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="weapons.xsd">
  <Weapon>
    <Name>Crowbar</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Starting</Deck>
    <Count>1</Count>
    <Category>Melee</Category>
    <Melee>
      <Range>0</Range>
      <Dice>1</Dice>
      <Accuracy>4</Accuracy>
      <Damage>1</Damage>
      <Overload>1</Overload>
      <Kill_Noise>false</Kill_Noise>
    </Melee>
    <Ranged />
    <Open_Door>true</Open_Door>
    <Door_Noise>false</Door_Noise>
    <Dual>false</Dual>
    <Special />
  </Weapon>
  <Weapon>
    <Name>Fire Axe</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Starting</Deck>
    <Count>1</Count>
    <Category>Melee</Category>
    <Melee>
      <Range>0</Range>
      <Dice>1</Dice>
      <Accuracy>4</Accuracy>
      <Damage>2</Damage>
      <Overload>1</Overload>
      <Kill_Noise>false</Kill_Noise>
    </Melee>
    <Ranged />
    <Open_Door>true</Open_Door>
    <Door_Noise>true</Door_Noise>
    <Dual>false</Dual>
    <Special />
  </Weapon>
  <Weapon>
    <Name>Ka-Bar</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Starting</Deck>
    <Count>1</Count>
    <Category>Melee</Category>
    <Melee>
      <Range>0</Range>
      <Dice>1</Dice>
      <Accuracy>3</Accuracy>
      <Damage>1</Damage>
      <Overload>1</Overload>
      <Kill_Noise>false</Kill_Noise>
    </Melee>
    <Ranged />
    <Open_Door>false</Open_Door>
    <Door_Noise>false</Door_Noise>
    <Dual>true</Dual>
    <Special>Add +1 die to another equipped Melee weapon.</Special>
  </Weapon>
  <Weapon>
    <Name>Pistol</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Starting</Deck>
    <Count>1</Count>
    <Category>Ranged</Category>
    <Melee />
    <Ranged>
      <Ammo_Type>Bullets</Ammo_Type>
      <Range_Min>0</Range_Min>
      <Range_Max>1</Range_Max>
      <Dice>1</Dice>
      <Accuracy>3</Accuracy>
      <Damage>1</Damage>
      <Overload>1</Overload>
      <Kill_Noise>true</Kill_Noise>
    </Ranged>
    <Open_Door>false</Open_Door>
    <Door_Noise>false</Door_Noise>
    <Dual>true</Dual>
    <Special />
  </Weapon>
  <Weapon>
    <Name>Rifle</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Starting</Deck>
    <Count>2</Count>
    <Category>Ranged</Category>
    <Melee />
    <Ranged>
      <Ammo_Type>Bullets</Ammo_Type>
      <Range_Min>1</Range_Min>
      <Range_Max>3</Range_Max>
      <Dice>1</Dice>
      <Accuracy>3</Accuracy>
      <Damage>1</Damage>
      <Overload>1</Overload>
      <Kill_Noise>true</Kill_Noise>
    </Ranged>
    <Open_Door>false</Open_Door>
    <Door_Noise>false</Door_Noise>
    <Dual>false</Dual>
    <Special />
  </Weapon>
  <Weapon>
    <Name>AAAHH!!</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Regular</Deck>
    <Count>4</Count>
    <Category>Zombie</Category>
    <Special>Place a Walker in the Zone immediately and discard this card.</Special>
  </Weapon>
  <Weapon>
    <Name>Canned Food</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Regular</Deck>
    <Count>2</Count>
    <Category>Bonus</Category>
    <Special>Discard: Gain 3 AP. May be used in the backpack.</Special>
  </Weapon>
  <Weapon>
    <Name>Chainsaw</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Regular</Deck>
    <Count>2</Count>
    <Category>Melee</Category>
    <Melee>
      <Range>0</Range>
      <Dice>5</Dice>
      <Accuracy>5</Accuracy>
      <Damage>2</Damage>
      <Overload>3</Overload>
      <Kill_Noise>true</Kill_Noise>
    </Melee>
    <Ranged />
    <Open_Door>true</Open_Door>
    <Door_Noise>true</Door_Noise>
    <Dual>false</Dual>
    <Special />
  </Weapon>
  <Weapon>
    <Name>Fire Axe</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Regular</Deck>
    <Count>1</Count>
    <Category>Melee</Category>
    <Melee>
      <Range>0</Range>
      <Dice>1</Dice>
      <Accuracy>4</Accuracy>
      <Damage>2</Damage>
      <Overload>1</Overload>
      <Kill_Noise>false</Kill_Noise>
    </Melee>
    <Ranged />
    <Open_Door>true</Open_Door>
    <Door_Noise>true</Door_Noise>
    <Dual>false</Dual>
    <Special />
  </Weapon>
  <Weapon>
    <Name>Flashlight</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Regular</Deck>
    <Count>2</Count>
    <Category>Bonus</Category>
    <Special>Search: Draw 2 cards. Light Source. May be used in the backpack.</Special>
  </Weapon>
  <Weapon>
    <Name>Katana</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Regular</Deck>
    <Count>2</Count>
    <Category>Melee</Category>
    <Melee>
      <Range>0</Range>
      <Dice>2</Dice>
      <Accuracy>4</Accuracy>
      <Damage>1</Damage>
      <Overload>2</Overload>
      <Kill_Noise>false</Kill_Noise>
    </Melee>
    <Ranged />
    <Open_Door>false</Open_Door>
    <Door_Noise>false</Door_Noise>
    <Dual>true</Dual>
    <Special />
  </Weapon>
  <Weapon>
    <Name>Kukri</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Regular</Deck>
    <Count>2</Count>
    <Category>Melee</Category>
    <Melee>
      <Range>0</Range>
      <Dice>2</Dice>
      <Accuracy>4</Accuracy>
      <Damage>2</Damage>
      <Overload>2</Overload>
      <Kill_Noise>false</Kill_Noise>
    </Melee>
    <Ranged />
    <Open_Door>false</Open_Door>
    <Door_Noise>false</Door_Noise>
    <Dual>false</Dual>
    <Special />
  </Weapon>
  <Weapon>
    <Name>Machete</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Regular</Deck>
    <Count>2</Count>
    <Category>Melee</Category>
    <Melee>
      <Range>0</Range>
      <Dice>1</Dice>
      <Accuracy>3</Accuracy>
      <Damage>2</Damage>
      <Overload>1</Overload>
      <Kill_Noise>false</Kill_Noise>
    </Melee>
    <Ranged />
    <Open_Door>false</Open_Door>
    <Door_Noise>false</Door_Noise>
    <Dual>true</Dual>
    <Special />
  </Weapon>
  <Weapon>
    <Name>Moltov</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Regular</Deck>
    <Count>4</Count>
    <Category>Ranged</Category>
    <Melee />
    <Ranged>
      <Ammo_Type />
      <Range_Min>1</Range_Min>
      <Range_Max>1</Range_Max>
      <Dice>0</Dice>
      <Accuracy>0</Accuracy>
      <Damage>0</Damage>
      <Kill_Noise>true</Kill_Noise>
    </Ranged>
    <Open_Door>false</Open_Door>
    <Door_Noise>false</Door_Noise>
    <Dual>false</Dual>
    <Special>Discard from Hand: Eliminate all Actors in the Targeted Zone</Special>
  </Weapon>
  <Weapon>
    <Name>Pistol</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Regular</Deck>
    <Count>1</Count>
    <Category>Ranged</Category>
    <Melee />
    <Ranged>
      <Ammo_Type>Bullets</Ammo_Type>
      <Range_Min>0</Range_Min>
      <Range_Max>1</Range_Max>
      <Dice>1</Dice>
      <Accuracy>3</Accuracy>
      <Damage>1</Damage>
      <Overload>1</Overload>
      <Kill_Noise>true</Kill_Noise>
    </Ranged>
    <Open_Door>false</Open_Door>
    <Door_Noise>false</Door_Noise>
    <Dual>true</Dual>
    <Special />
  </Weapon>
  <Weapon>
    <Name>Sawed-Off</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Regular</Deck>
    <Count>4</Count>
    <Category>Ranged</Category>
    <Melee />
    <Ranged>
      <Ammo_Type>Shells</Ammo_Type>
      <Range_Min>0</Range_Min>
      <Range_Max>1</Range_Max>
      <Dice>2</Dice>
      <Accuracy>3</Accuracy>
      <Damage>1</Damage>
      <Overload>2</Overload>
      <Kill_Noise>true</Kill_Noise>
    </Ranged>
    <Open_Door>false</Open_Door>
    <Door_Noise>false</Door_Noise>
    <Dual>true</Dual>
    <Special>Reload.</Special>
  </Weapon>
  <Weapon>
    <Name>Sniper Rifle</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Regular</Deck>
    <Count>2</Count>
    <Category>Ranged</Category>
    <Melee />
    <Ranged>
      <Ammo_Type>Bullets</Ammo_Type>
      <Range_Min>1</Range_Min>
      <Range_Max>3</Range_Max>
      <Dice>1</Dice>
      <Accuracy>3</Accuracy>
      <Damage>2</Damage>
      <Overload>1</Overload>
      <Kill_Noise>true</Kill_Noise>
    </Ranged>
    <Open_Door>false</Open_Door>
    <Door_Noise>false</Door_Noise>
    <Dual>false</Dual>
    <Special>Sniper.</Special>
  </Weapon>
  <Weapon>
    <Name>Water</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Regular</Deck>
    <Count>2</Count>
    <Category>Bonus</Category>
    <Special>Discard: Gain 3 AP. May be used in the backpack.</Special>
  </Weapon>
  <Weapon>
    <Name>AAAHH!!</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Ultrared</Deck>
    <Count>2</Count>
    <Category>Zombie</Category>
    <Special>Place a Walker in the Zone immediately and discard this card.</Special>
  </Weapon>
  <Weapon>
    <Name>Army Sniper Rifle</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Ultrared</Deck>
    <Count>1</Count>
    <Category>Ranged</Category>
    <Melee />
    <Ranged>
      <Ammo_Type>Bullets</Ammo_Type>
      <Range_Min>1</Range_Min>
      <Range_Max>4</Range_Max>
      <Dice>2</Dice>
      <Accuracy>3</Accuracy>
      <Damage>2</Damage>
      <Overload>1</Overload>
      <Kill_Noise>true</Kill_Noise>
    </Ranged>
    <Open_Door>false</Open_Door>
    <Door_Noise>false</Door_Noise>
    <Dual>false</Dual>
    <Special>Sniper.</Special>
  </Weapon>
  <Weapon>
    <Name>Golden AK-47</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Ultrared</Deck>
    <Count>1</Count>
    <Category>Ranged</Category>
    <Melee />
    <Ranged>
      <Ammo_Type>Bullets</Ammo_Type>
      <Range_Min>1</Range_Min>
      <Range_Max>2</Range_Max>
      <Dice>3</Dice>
      <Accuracy>4</Accuracy>
      <Damage>2</Damage>
      <Overload>3</Overload>
      <Kill_Noise>true</Kill_Noise>
    </Ranged>
    <Open_Door>false</Open_Door>
    <Door_Noise>false</Door_Noise>
    <Dual>false</Dual>
    <Special />
  </Weapon>
  <Weapon>
    <Name>Golden Kukri</Name>
    <Set>Fort Hendrix</Set>
    <Deck>Ultrared</Deck>
    <Count>1</Count>
    <Category>Melee</Category>
    <Melee>
      <Range>0</Range>
      <Dice>4</Dice>
      <Accuracy>4</Accuracy>
      <Damage>2</Damage>
      <Overload>2</Overload>
      <Kill_Noise>false</Kill_Noise>
    </Melee>
    <Ranged />
    <Open_Door>false</Open_Door>
    <Door_Noise>false</Door_Noise>
    <Dual>false</Dual>
    <Special />
  </Weapon>
  <Weapon>
